### ISSUE TITLE
When storing a subscription NH cannot determine whether it should call `Save` or `Update`

### ISSUE THREAD

**Issue by sveinfid** [Particular/NServiceBus.NHibernate#101]
This is probably the same issue as #99, but for subscriptions instead of timeouts.
## Symptoms

When storing subscriptions with the NHibernate persistence the following warning is raised:

> 2015-05-14 12:47:11,594 [24] WARN  NHibernate.Engine.ForeignKeys [(null)] - Unable to determine if NServiceBus.Unicast.Subscriptions.NHibernate.Subscription with assigned identifier NServiceBus.Unicast.Subscriptions.NHibernate.Subscriptionis transient or detached; querying the database. Use explicit Save() or Update() in session to prevent this.
## Who's affected

Everyone using NHibernate persistence to store subscriptions.
## Versions

Newest stable NuGet packages:
- Iesi.Collections.4.0.1.4000
- log4net.2.0.0
- NHibernate.4.0.3.4000
- NServiceBus.5.2.0
- NServiceBus.Host.6.0.0
- NServiceBus.Log4Net.1.0.0
- NServiceBus.NHibernate.6.1.2

**Comment by SimonCropp** [comment]
@SzymonPobiega seems like an easy fix. want me to have a go at it?

**Comment by SzymonPobiega** [comment]
@SimonCropp not sure about that. Subscription messages can get duplicated in which case `SaveOrUpdate` makes sense. Also, the volume of these messages if very small compared to the timeout messages so the benefit here would be relatively smaller.

**Comment by SimonCropp** [comment]
so can we just tell NH not to annoy us?

**Comment by SzymonPobiega** [comment]
@SimonCropp I think the current solution is also broken. Suppose you get a duplicate `Subscribe` message (might happen in case a subscribing endpoint is scaled out). If these two messages happen to be picked up by different threads than it is essentially two threads executing the following pseudo-code inside `SaveOrUpdate`:

```
found = TryLoadFromDatabase()
if (found)
{
  this.Update()
}
else
{
   this.Save()
}
```

so a classic race condition.If both execute the query in the same time, we would get an exception.

Conclusion: in order to work, we would need a higher transaction isolation level.

**Comment by janovesk** [comment]
More customers are [noticing](https://nservicebus.desk.com/agent/case/12748) this.

**Comment by janovesk** [comment]
Would it work to just use 

```
found = TryLoadFromDatabase()
if (!found)
{
   this.Save()
}
```

in this scenario? What does the update provide? You can't update a subscription?

**Comment by SzymonPobiega** [comment]
@janovesk this might result in an exception because multiple threads might process similar subscription requests (coming from different instances of same endpoint). 

The update is used when the version changes so if you subscribed to V4 and you deployed an instances the processes V5, the entry in subscription store will get updated. That said, I am not sure if this is really necessary.

**Comment by SzymonPobiega** [comment]
@Particular/persistence-maintainers is this something we should consider fixing in V6?

**Comment by HEskandari** [comment]
Shouldn't this be treated as a bug? In that case I'd fix it in v5 (or lower) and port it to v6 as well.

**Comment by SzymonPobiega** [comment]
Technically it is not a bug because FLR takes care of the problem without user even noticing.

**Comment by DavidBoike** [comment]
And it could be fixed at any time. Not critical for V6.

**Comment by SzymonPobiega** [comment]
We added immediate retries to cover for concurrency errors when updating the subscription store.
