### ISSUE TITLE
Version 6.2 causes exceptions if multiple threads are creating the saga tables concurrently

### ISSUE THREAD

**Issue by AlanMullett** [Particular/NServiceBus.NHibernate#104]
@SzymonPobiega

Thank you for release 6.2, Sean informed me that it had been released.

However, further to #96 the changes cause exceptions to be throw by NHibernate, specifically when line 21 of ...\SharedSession\Installer.cs is being called on more than one thread with the same configuration it demonstrates that the NHibernate code is taking time between investigating and performing the table create as it throws:

*System.Data.SqlClient.SqlException: There is already an object named 'SagaData' in the database.*

This doen't happen everytime the table is created but it is much more noticeable when using remote databases, especially SQL Azure where it happens frequently.  With a local DB is rarely happens.

I know that I am probably using an unusual configuration and so I've put together an example of how we are using NServiceBus with multiple endpoints serving a single saga in an assembly.  We do this because upstream we have a process that dumps potentially thousands of messages in seconds onto the saga and the start saga handler can take several seconds per message.  This means that any reply from other handlers back to the saga may not be seen for some time as they are at the back of the queue.  So we divert the reply to another endpoint that is pretty much empty all the time.

This example can be found in the UsingMultipleEndpoints solution within https://github.com/AlanMullett/UsingNServiceBus.  

I have found that simply lock()ing the above line resolves the issue, and given that most people appear to be using this class with only a single endpoint this will only affect the people like myself who are attempting to run multiple endpoints in a process with visibility of the same saga data class.  However I'm sure you will have a much more elegant solution.

Thank you

Alan.

**Comment by SzymonPobiega** [comment]
Alan, you're correct that locking would help here. What I am not sure though is if this should be fixed on the framework level. NServiceBus initialization process is not thread-safe internally. The problem here is that multiple endpoints try to modify the shared state which is the database schema.

The fact that you have multiple endpoints involved in a single saga is not unusual at all. On the contrary, this is actually what we recommend since endpoints are there to provide proper QoS. What is unusual though is the fact that you are starting all these endpoints concurrently. I'd suggest to remove the multi threaded start. I know that there is a cost in start-up time but that should be not a big deal since in production your endpoints would spend most of their time working, not starting, anyway.

Feel free to re-open that issue if you disagree and you still think we should handle that on NServiceBus level.

**Comment by AlanMullett** [comment]
Thank you for your feedback, it's most appreciated.  I've changed the code to start up the endpoints sequentially which has solved the problem and so I'm happy to agree with your closure of this issue.

Alan.
