### ISSUE TITLE
Map DateTime properties as timestamp NHibernate type

### ISSUE THREAD

**Issue by sveinfid** [Particular/NServiceBus.NHibernate#105]
NHibernate by default maps DateTime properties as datetime NHibernate type

Using SQL Server this is a bit inconvenient as it truncates at the second level.

If it would map using the timestamp NHibernate type instead, it wouldn't truncate at the second level, but be as specific as the database supports (e.g. SQL Server rounds to the nearest 3.33 ms)

NServiceBus.NHibernate already maps to timestamp NHibernate type when mapping rowVersionProperty (if it is of type DateTime), so I don't think it should be a problem to do this more generally when mapping properties of type DateTime.

Ref. 1: http://nhibernate.info/doc/nh/en/index.html#mapping-types-basictypes

Ref. 2: http://stackoverflow.com/questions/2033630/datetime-precision-in-nhibernate-and-support-for-datetime2-in-nhibernate-schemee

**Comment by ramonsmits** [comment]
@sveinfid Its NHibernate that does the truncating. Its the difference between the NHibernate types `DateTime` and `Timestamp`. The first has no milliseconds.

When you use `Timestamp` you have increased precision but this gets rounded by MSSQL.

## Breaking change

Changing this would be a breaking change unless we make it configurable.

### Column type

Using a different db column type would be a breaking change when targeting `datetime2`


## NHibernate type

When we would configure `System.DateTime` to be of NHibernate type `Timestamp` then NHiberate will still use TSQL `datetime` type but have increased precision. This would not break the schema but would still be a breaking change in behavior.


## Alternatives

### Custom mapping

Create your own custom mapping or mapping convention using the mapping capabilities of NHibernate itself of any of the other mapping frameworks like 

### Using a long instead of DateTime

Why do you care about the precision? If you use if for your application to measure durations then my guess is that you cannot use `Timestamp` too do to MSSQL rounding behavior. Aren't you better of by using an `int` or `long` that uses 'milliseconds since unix epoch'?


## Custom build

I just researched if it is simple to do. I have not tested this yet but I think this should work.

https://github.com/ramonsmits/NServiceBus.NHibernate/tree/datetime-to-timestamp

You can adjust it to `NHibernateUtil.DateTime2` if that would be your preferred column type.
