### ISSUE TITLE
Make usage of NHibernate compatible with `SET NOCOUNT ON` DB-wide setting

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#112]
### Symptoms

When `NOCOUNT` is set to `ON` our NH persistence does not work. Even if it can be hacked to get working via adding the proper `SET NOCOUNT OFF` setting as part of session initialization, there are places e.g. `TryRemoveTimeoutEntity` where it cannot be done. 

### Who's affected

Users that have `NOCOUNT ON` on DB level

### Potential solution

Extend the API that allows to customize how sessions are created so that users can customize each and every session used, not only the one used for saga and outbox.

**Comment by SzymonPobiega** [comment]
Based on desk case 12110

**Comment by yossita** [comment]
Just a minor nitpick: NOCOUNT ON is set at the instance level

**Comment by johnsimons** [comment]
Sorry for the ignorant question but what is the problem with NOCOUNT ON/OFF ?

**Comment by SzymonPobiega** [comment]
@johnsimons NHibernate requires NOCOUNT OFF to function properly. When NOCOUNT is ON on the instance level, in order for NH persistence to work, it needs to set it to OFF for each connection we open.

**Comment by johnsimons** [comment]
> NHibernate requires NOCOUNT OFF to function properly

Is this documented anywhere ? Don't we just need to point our doco to whatever doco states it ?

**Comment by johnsimons** [comment]
Here is another answer to support my previous answer, http://stackoverflow.com/a/17550837/90882

**Comment by ramonsmits** [comment]
SET NOCOUNT OFF is needed for correct optimistic concurrency control and consistency. You really want to know how many rows are affected with doing an UPDATE or DELETE. Not having the row count returned makes it impossible to guarantee data consistency.

This is not a problem that should be 'solved' by NServiceBus.NHibernate.

Although I'm not 100% sure I think that the following should work. Each time a connection is created we call `SET NOCOUNT OFF` as this is required for NHibernate. I currently don't have access to a actual SQL server to change this setting at the instance level.

```
public class CustomDriverConnectionProvider : NHibernate.Connection.DriverConnectionProvider
{
    public override System.Data.IDbConnection GetConnection()
    {
        var conn = base.GetConnection();
        DisableNoCount(conn);
        return conn;
    }

    private void DisableNoCount(System.Data.IDbConnection connection)
    {
        using (var command = connection.CreateCommand())
        {
            command.CommandText = "SET NOCOUNT OFF";
            command.ExecuteNonQuery();
        }
    }
}
```

This requires to the driver connection provider to be configured:

```
<appSettings>
  <add
      key="NServiceBus/Persistence/NHibernate/connection.provider"
      value="CustomDriverConnectionProvider, MyAssembly" />
</appSettings>
```

or create a custom NHibernate configuration object and pass it to NServiceBus.

**I really consider this as being a workaround!** This should only be applied in legacy environments where operations is not able to just create an additional SQL instance on either the same or a separate server.

**Comment by ramonsmits** [comment]
@yossita I just tested this connection provider with a SQL instance with NOCOUNT ON and it works as expected.

**Comment by yossita** [comment]
@ramonsmits , thanks, I'll test the custom provider and update back to you with updates.

Something which worked for us was to inject a custom batch batcher to inject nocount on before each batch, but the TimeoutPersister tries to remove the timeout entity using a delete statement, it is not batched and nocount is still on:

   var queryString = string.Format("delete {0} where Id = :id", typeof(TimeoutEntity));

   found = session.CreateQuery(queryString)
      .SetParameter("id", timeoutId)
      .ExecuteUpdate() > 0;

By the way, since the code gets the entity before, why not call session.delete(te);?

And yes, I agree this is a workaround bordering a nasty hack - we're paying for years of technical debt. We're exploring other options as well like switching our NSB DBs to another instance.

**Comment by ramonsmits** [comment]
@yossita The reason for the "delete {0}" is that there is a bug in NHibernate that prevents the `ISession.Delete(..)` on a stateless session.

The custom connection provider should execute it once each time a (stateless) session is created.

**Comment by a-belevich** [comment]
It looks like 

    bool TryGetConnection(out IDbConnection connection)
    {
        DbConnectionProvider.TryGetConnection(out connection, ConnectionString);
    }

prevents timeout persister from using the fixed connection provider. Replacing this function with 

        connection = SessionFactory.GetConnection();
        return true;

solves the problem.

**Comment by ramonsmits** [comment]
@a-belevich Solves which problem and when? Have you been using the custom connection provider?

`IDbConnectionProvider` is used to share the same IDbConnection across all persistence logic to allow to work without DTC and share the same transaction for reliability

Are you using the outbox?

Your fix results in a new connection to be created. This is unwanted when using the outbox.

**Comment by yossita** [comment]
@ramonsmits Session.Delete worked fine with NHibernate 4.0.0.4000 and stateless session, but it still doesn't use the custom connection factory. With a custom batcher that injects NOCOUNT OFF it worked as expected.

**Comment by ramonsmits** [comment]
@yossita I'm using nuget 4.0.3.4000 of NHibernate.

I have a sample that creates a saga with a timeout and waits until the timeout is handled. I only need the nhibernate custom connection provider. The change that @a-belevich suggested is not required and also not the custom batcher.

See it working here: https://youtu.be/XX4YHJzyHG4

Also works with outbox, tested with MSMQ, SQL Server and disabled DTC.

**Comment by a-belevich** [comment]
@ramonsmits I assume your sample works because `RemoveTimeoutEntityBySagaId` doesn't check result of `ExecuteUpdate()`. Our problem is about SLR, not sagas. So, just create handler that always throws exception, configure SLR and send the command.

Original behavior is: after all FLR attempts, it tries to send the message to SLR, and throws exception when trying to insert record into TimeoutEntity table. We fixed it by injecting custom batcher, that executes SET NOCOUNT OFF before every batch. It also can be fixed by your custom connection provider, and I like this approach better.

However, after original exception is fixed, in case of SLR (unlike sagas) new problem arouse: `TimeoutPersister.TryRemoveTimeoutEntity` always returns false, because `ExecuteUpdate()` always returns -1. So, `TimeoutDispatcherProcessorBehavior.Handle` doesn't actually send messages for SLR attempt; it just silently deletes them from `TimeoutEntity`.

This issue is not fixed by the batcher injection (because no batchers are used here), unless deleting with `CreateQuery` would be replaced with `session.delete` (as @yossita suggests). It also cannot be fixed with injecting new NHibernate's connection provider, because `connection` parameter of `TryRemoveTimeoutEntity` can be created in 2 ways: using `DBConnectionProvider` (that takes connection instance from `PipelineExecutor.CurrentContext`), or from `NHibernate's SessionFactory`. And the former way (that actually works) appears to ignore `NServiceBus/Persistence/NHibernate/connection.provider` parameter. So, NOCOUNT remains ON. 

If you think it's critical to re-use connections from `PipelineExecutor.CurrentContext` here, we'll need some way to customize these connections as well.

**Comment by ramonsmits** [comment]
@a-belevich The DELETE result is checked as I'm testing the latest release of NServiceBus.NHibernate.

SLR is also working fine, as well as Defer. Timeouts work correctly and are also deleted correctly.

You are correct that it there is an connection in the context then this connection should indeed be initialized correctly. If this connection would be created outside of NHibernate then the custom connection provider will not be able to execute `SET NOCOUNT OFF`.

I'm testing with MSMQ and have tested with DTC and without DTC in combination with the outbox.

- What transport are you using? 
- Are you using the outbox?
- Are you using DTC?
- Can you share your NServiceBus initialization?

**Comment by a-belevich** [comment]
@ramonsmits SQL Server transport. No Outbox. Yes.

```
    public class EndpointConfig : IConfigureThisEndpoint, AsA_Server
    {
        public void Customize(BusConfiguration configuration)
        {
            configuration.UseTransport<SqlServerTransport>().DefaultSchema("workflow");

            configuration.UsePersistence<InMemoryPersistence>();
            configuration.UsePersistence<NHibernatePersistence, StorageType.Timeouts>();
            
            configuration.EndpointName(GetConfigValue("BusEndpointName", true));

            configuration.UseSerialization<JsonSerializer>();

            configuration.EnableInstallers();
            BusConfig.ApplyMessagesConventions(configuration);
        }
    }

<?xml version="1.0"?>
<configuration>
  <MessageForwardingInCaseOfFaultConfig ErrorQueue="error" />
  <TransportConfig MaximumConcurrencyLevel="5" MaxRetries="5" MaximumMessageThroughputPerSecond="0" />
  <SecondLevelRetriesConfig Enabled="true" TimeIncrease="00:00:10" NumberOfRetries="3" />

  <appSettings>
    <add key="BusEndpointName" value="Workflow" />
    <add key="NServiceBus/Persistence/NHibernate/default_schema" value="workflow"/>
    <add key="NServiceBus/Persistence/NHibernate/connection.provider" value="Workflow.Common.Infrastructure.Bus.NoCountSafeDriverConnectionProvider, Workflow.Common.Infrastructure" />
  </appSettings>

  <hibernate-configuration xmlns="urn:nhibernate-configuration-2.2">
    <session-factory>
      <property name="adonet.factory_class">Workflow.Common.Infrastructure.Bus.NoCountSafeBatcherFactory, Workflow.Common.Infrastructure</property>
      <property name="show_sql">true</property>
    </session-factory>
  </hibernate-configuration>

  <connectionStrings>
    <add name="NServiceBus/Transport" connectionString="..."/>
    <add name="NServiceBus/Transport/error" connectionString="..."/>
    <add name="NServiceBus/Transport/audit" connectionString="..."/>
    <add name="NServiceBus/Transport/Particular.ServiceControl" connectionString="..." />
    <add name="NServiceBus/Persistence/NHibernate/Timeout" connectionString="..." />
    <add name="NServiceBus/Persistence/NHibernate/Saga" connectionString="..." />
  </connectionStrings>
</configuration>
```

**Comment by ramonsmits** [comment]
@a-belevich This is interesting. I think that when using the SQL transport, persistence is using the `IDbConnection` of the SQL transport. The SQL transport `IDbConnection` is not created via NHibernate so therefore `SET NOCOUNT OFF` could not be executed.

I'm changing my sample to use SQL transport.

**Comment by ramonsmits** [comment]
@a-belevich @yossita  Its not working with the SQL transport. Both the SQL transport and NHibernate persistence share their transaction on the pipeline context via the key `SqlConnection-{0}`.

The fix is easy and you even have choices:

- Make sure that the transport and persistence cannot share the same connection by configuring a different connection string. Just add a space character or change the order of connection string arguments.
- Enable the outbox, which makes sure that the connection will not be shared between the transport and persistence.
- Disable distributed transactions, this makes sure that persistence will not share the SQL transport `IDbConnection` **but does not use a `TransactionScope`** which can result in more then once delivery which requires your sagas and handlers to be idempotent.

The first solution relies on DTC, the second on the outbox and does not need DTC, the third does not use the outbox resulting in you being responsible for idempotency.

The first resembles the transaction behavior when using MSMQ and NHibernate persistence as this also relies on MSDTC for reliability except for the difference that MSMQ is a local resource.

Unfortunately, there is not an option in our API that can disable connection sharing between the sql transport and nhibernate persistence and still make use of a `TransactionScope` to make use of lightweight transaction manager so that DTC is not required.

Also unfortunate that there is not a way to override SQL connection creation behavior in the SQL transport as is possible in NHibernate by having some kind of connection provider that you can either override or be able to execute SQL when the connection is created.

**Comment by yossita** [comment]
@ramonsmits, changing the connection string for timeouts + the custom connection provider solved our issue. Outbox and no transactionality are not valid options for us.

**Comment by a-belevich** [comment]
@ramonsmits Thank you, it works.

**Comment by SzymonPobiega** [comment]
Resolved via https://github.com/Particular/NServiceBus.SqlServer/pull/87
