### ISSUE TITLE
TimeoutData.OwningTimeoutManager value is not restored

### ISSUE THREAD

**Issue by cremor** [Particular/NServiceBus.NHibernate#287]
When I read through your code I noticed that the property `TimeoutData.OwningTimeoutManager` is saved in the database (via the `TimeoutEntity.Endpoint` property in the [Add method](https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs#L87)) but when the `TimeoutData` is restored (in the [MapToTimeoutData method](https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/TimeoutPersisters/TimeoutPersister.cs#L168)) the `OwningTimeoutManager` is not set.

Since the `OwningTimeoutManager` property isn't used for anything in the core this isn't a proplem right now. But shouldn't it be restored anyway in case the core needs it sometime in the future?

**Comment by MarcinHoppe** [comment]
The `OwningTimeoutManager` property allows different endpoints to store their timeouts in a single table. All persisters that share table or collection between endpoints store their own endpoint name in this property and use it as a query parameter when polling for timeouts to dispatch. The core does not need this value later on because it is always implicitly equal the current endpoint name.

Note that it is possible for a persister to use a separate table for each endpoint and this value is not even necessary in such a case. A good example of this might be the [SQL persistence](https://docs.particular.net/nservicebus/sql-persistence/).

Does this explanation help?

**Comment by cremor** [comment]
Yes, that makes sense. Thanks.
