### ISSUE TITLE
Deadlocks while persisting saga data collections

### ISSUE THREAD

**Issue by Feanathiel** [Particular/NServiceBus.NHibernate#297]
**Problem**
When using saga data that contains collections I'm getting quite a few deadlocks (SQL Server). The primary saga data (inheriting IContainSagaData) is persisted properly, but collections (which are stored in a seperate table) are not. It seems that these collections cause table locks thus causing deadlocks while processing a lot of saga messages (even if saga's aren't handling concurrent messages).

![non-optimized](https://user-images.githubusercontent.com/717296/28156255-4c8f919e-67b2-11e7-80d0-3c61127b967c.PNG)

**Possible solution**
It would be nice to add a non-unique index on the foreign key, avoiding the need for a full table scan to find the proper collection data for a saga. Also I would like to add a new column, a generated guid, as a primary key. This avoids a table rescan when deleting the indirect saga data.

![optimized](https://user-images.githubusercontent.com/717296/28156256-4c91c536-67b2-11e7-9eaa-9ebfcf846164.PNG)

Relevant code: https://github.com/Particular/NServiceBus.NHibernate/blob/1c282a2aaf1804f40e227bb12647734a58443493/src/NServiceBus.NHibernate/SagaPersisters/SagaModelMapper.cs#L188

**Comment by SzymonPobiega** [comment]
@Feanathiel thanks for reporting this. We're investigating ways to tap into NHibernate's script generation to include the index on the FK.

**Comment by SzymonPobiega** [comment]
@Feanathiel the fix has been merged to `develop`. It will be released with the next minor. In the meantime please add the relevant index manually. Also, keep in mind that the way NHibernate schema generation works is it does not update the existing schema elements (such as tables). It only creates them if they don't exist.

**Comment by Feanathiel** [comment]
@SzymonPobiega Thank you for taking your time implementing this change and the remark. I will add the indices manually right now, since the tables already exist. I will look forward for the new release in the meantime. Have a great day!

**Comment by Himanshu55007** [comment]
I am still facing this problem in version 6.4.0

**Comment by ramonsmits** [comment]
@Himanshu55007 What problem? Deadlocks on sagas? Is the index on the child table present? Could you create a post on our forum and include as much details as possible at https://discuss.particular.net/ ?

**Comment by dchidraw** [comment]
Thanks ramonsmits. Index on child table is not present and we believe it works by adding an index on the child table. However, saga used to work with V5 endpoints without an index. Wondering what is causing the V6 endpoint to explicitly have the index on the table.

**Comment by dchidraw** [comment]
@ramonsmits - Also, we believe it would be good if NSB endpoint takes care of index creation implicitly on the backend if it is mandatory.

**Comment by ramonsmits** [comment]
The index is being created from NServiceBus.NHibernate 7.1.6 onwards which is for NServiceBus 6. If you are using NServiceBus 5 or prior you will need to create this index manually or upgrade to NServiceBus 6.

Second, child collections can be list items or actual entities.  This depends on the presence of an Id property:

- When NOT specifying an Id property on the child item every save of the saga will result in ALL child items to be deleted and inserted. This can result in IO issues if the child collection contains many or large items.
- When specifying an Id property the child item becomes an entity. Adding or Removing items will not result in reinserting the whole collection but will only DELETE or INSERT specific records.


Depending on the type of performance issues you should either add the Index or have an Id property to resolve your performance issue.

**Comment by ramonsmits** [comment]
To add info for other that might land on this issue:

Deadlocks can in some cases not be prevented and occur to keep saga instance state consistent. If deadlocks occur very frequently that this can be hurting performance.

https://docs.particular.net/persistence/nhibernate/saga-concurrency

Also, if using log4net, deadlocks are written as ERRORS although these are handled by NServiceBus and retries. Usually the message will be processed correctly the second time.

**Comment by dchidraw** [comment]
Thanks Ramon.

We are using NServiceBus.NHibernate 7.2.2 and still the index is not getting created on the child table. What are we doing wrong? We have seen if index gets created then we are not seeing the deadlock scenario.

<package id="NServiceBus.NHibernate" version="7.2.2" targetFramework="net461" />


Thanks,
Datta Chidrawar
Assistant Manager - Telematics & CDI
dchidraw@arifleet.com<mailto:dchidraw@arifleet.com>
P 856-778-1500 x 52823
C 732-692-7906

ARI Technology Innovation Center
2001 Bishops Gate Blvd,
Mt Laurel, NJ 08054
[Description: Description: EmailSig2blue]

**Comment by Feanathiel** [comment]
Is it a new table? If I remember correctly the table will only be created once, and is never updated with the indices. Just making sure.

**Comment by dchidraw** [comment]
We dropped and recreated table by installing the endpoint but still do not see the index being created.

Sent from my iPhone

On Nov 6, 2018, at 6:57 AM, Feanathiel <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it a new table? If I remember correctly the table will only be created once, and is never updated with the indices. Just making sure.

**Comment by dchidraw** [comment]
From: Chidrawar, Datta
Sent: Monday, November 12, 2018 2:02 PM
To: 'support@particular.net '
Subject: FW: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections



From: Chidrawar, Datta
Sent: Monday, November 12, 2018 2:01 PM
To: 'support@particular.net'
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections

Thanks Ramon.

Upon further review we noticed that adding an Id property does NOT create an index on the foreign key column in the child table causing the deadlock on delete operation on the parent table. Is this the behavior have you seen?

Attaching the Entity and DDL's for the table. Also note that we are using NServiceBus version 6.4.0 and NServiceBus.NHibernate version 7.2.2.

We really appreciate your help and support in this matter. Thanks in advance!!

Thanks,
Datta

From: support@particular.net [mailto:support@particular.net]
Sent: Monday, November 12, 2018 12:08 PM
To: Chidrawar, Datta
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections



Hi,

I've looked at your code and tried to use your saga to try and reproduce your issue. This project is available at the following location:

- https://github.com/ramonsmits/docs.particular.net/tree/support/nhibernate-sagas-complextype-index/samples/nhibernate/simple/NHibernate_8

I indeed saw that an index wasn't created on the child item. In order to resolve that you must make the child item an entity. You do this by adding an Id Property as shown here:

- https://github.com/ramonsmits/docs.particular.net/blob/support/nhibernate-sagas-complextype-index/samples/nhibernate/simple/NHibernate_8/Server/TripDistanceSagaData.cs#L32


If you add this a new table will be created which will have both a clustered index because of the Id property but will also have an index for the foreign key relation.

Not only will this make retrieval of child items faster but it will in general result in less IO. In your current NHibernate entity model EVERY saga save will result in the deletion and reinserting of all childitems. This is probably not an issue for this model as I think it will only contain at most 3 items but this can add up if you have large child item collections.

Let me know if this works for you.

You might spot a few other changes too:

- Added RowVersion attribute for optimistic concurrency control
- Using a shared DateTime.UtcNow for all datetime assignments in the saga to align the value and to make sure it isn't using a Local time as these are likely be affected by daylight saving time (DST).



Regards,
Ramon

--------------- Original Message ---------------
From: support@particular.net [support@particular.net]
Sent: 2018-11-07 17:58
To: dchidraw@arifleet.com
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections


Sorry, I missed your comment on the github issue:

- https://github.com/Particular/NServiceBus.NHibernate/issues/297#issuecomment-436230023

 I'll test with the provided saga data structure and report my findings..


--------------- Original Message ---------------
From: support@particular.net [support@particular.net]
Sent: 2018-11-07 17:44
To: dchidraw@arifleet.com
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections


Hi,

Do you have some results to share after a week?

Please let me know if this needs assistance or if we can close it.

Regards,
Ramon


--------------- Original Message ---------------
From: Chidrawar, Datta [dchidraw@arifleet.com]
Sent: 2018-11-01 20:32
To: support@particular.net
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections

Thanks Ramon. We will look into it and get back to you. Thanks.

From: support@particular.net [mailto:support@particular.net]
Sent: Wednesday, October 31, 2018 11:22 AM
To: Chidrawar, Datta
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections



Hi,

Some observations and solution strategies:

- Your child object does not have an Id property and due to this NHibernate will *always* delete all child items and reinsert them at every save which can make your IO pretty heave if the number of child items are pretty heavy. I advice to really dive into NHibernate to understand how it works.

- You can use a Version property as this will make optimistic concurrency easier https://docs.particular.net/persistence/nhibernate/saga-concurrency#explicit-version

- If optimistic concurrency hurts performance due to a lot of deadlocking and/or OCC revision check errors you might want to use pessimistic locking by setting the locking hint https://docs.particular.net/persistence/nhibernate/saga-concurrency#adjusting-the-locking-strategy

- The error you share is logged by NHibernate and not by NServiceBus. This is an NHibernate ERROR log entry and can be ignored, you should better monitoring the WARN and ERROR log entries generated by NServiceBus.

- If you occasionally see a deadlock than just ignore it. This is perfectly normal in most environments and any error will be retries by the NServiceBus recovery mechanism.


Please let me know if this helps!

Regards,
Ramon


--------------- Original Message ---------------
From: support@particular.net [support@particular.net]
Sent: 2018-10-30 22:37
To: dchidraw@arifleet.com
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections



Thanks for the provided data. I'll examine this and get back to you Tomorrow.


-- Ramon

--------------- Original Message ---------------
From: Chidrawar, Datta [dchidraw@arifleet.com]
Sent: 2018-10-30 17:33
To: support@particular.net
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections

Yes Ramon.

Here are the details. (Attached DDL for the tables & saga class files)

Error:
ERROR NHibernate.AdoNet.AbstractBatcher [(null)] - Could not execute command: DELETE FROM TripDistanceSagaData WHERE Id = :p0 AND OriginalMessageId = :p1 AND Originator = :p2 AND TripKey = :p3 AND SourceKey = :p4 AND InvalidDistance = :p5 AND StartLatitude = :p6 AND StartLongitude = :p7 AND EndLatitude = :p8 AND EndLongitude = :p9 AND IsCreated = :p10
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00060: deadlock detected while waiting for resource
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)

Please let me know if you need any additional information.

Thanks,
Datta Chidrawar
Assistant Manager - Telematics & CDI
dchidraw@arifleet.com<mailto:dchidraw@arifleet.com>
P 856-778-1500 x 52823
C 732-692-7906

ARI Technology Innovation Center
2001 Bishops Gate Blvd,
Mt Laurel, NJ 08054
[Description: Description: EmailSig2blue]



From: support@particular.net [mailto:support@particular.net]
Sent: Tuesday, October 30, 2018 12:20 PM
To: Chidrawar, Datta
Subject: RE: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections



Hi is the following comment from you?

- https://github.com/Particular/NServiceBus.NHibernate/issues/297#issuecomment-434346534

Can you please share your log file, the saga data class files, and also your database schema from your Oracle DB?

These would be very helpful for diagnosing your issue and to see if you actually have an issue.

Regards,
Ramon

--------------- Original Message ---------------
From: Datta [dchidraw@arifleet.com]
Sent: 2018-10-30 16:50
To: support@particular.net
Subject: Support Request: Sage - ORA-00060: deadlock detected while waiting for resource - Error on Deleting child collections

Hi,

Our issue seems like to be related to the below link

https://github.com/Particular/NServiceBus.NHibernate/issues/297

Here are the details.

Environment -
- NSB - V4.6.0, NServiceBus.NHibernate V 7.2.2
- Oracle 12c as Persistance for Saga
- Two tables to store saga data : Parent: Child: has collection against a parent record.

Any help is greatly apprecaited.Error! Filename not specified.

Error! Filename not specified.
 Error! Filename not specified.

Error! Filename not specified.
 Error! Filename not specified.
 Error! Filename not specified.

ref:_00DD0mqNg._500D01qubd5:ref

﻿using NServiceBus;
using NServiceBus.SagaPersisters.NHibernate;
using System;
using System.Collections.Generic;
using Telematics.Trip.DistanceAggregator.Contracts.Commands;

namespace Telematics.Trip.DistanceAggregator.Endpoint.Saga
{
    public class TripDistanceSagaData : IContainSagaData
    {
        public TripDistanceSagaData()
        {
            DistancesData = new List<TripDistanceData>();

            this.IsCreated = false;
        }
        [RowVersion]
        public virtual int Version { get; set; }
        public virtual Guid Id { get; set; }
        public virtual string OriginalMessageId { get; set; }
        public virtual string Originator { get; set; }
        public virtual Int64 TripKey { get; set; } // This changed from decimal to int in support of NSB upgrade v5.x to 6.x; also, "unique" atribute removed per NSB Upgrade
        public virtual decimal SourceKey { get; set; }
        public virtual bool InvalidDistance { get; set; } //Indicates the distance should not be used
        public virtual IList<TripDistanceData> DistancesData { get; set; }
        public virtual decimal? StartLatitude { get; set; }
        public virtual decimal? StartLongitude { get; set; }
        public virtual decimal? EndLatitude { get; set; }
        public virtual decimal? EndLongitude { get; set; }
        public virtual bool IsCreated { get; set; }
    }

    public class TripDistanceData
    {
        public virtual Guid Id { get; set; }
        public virtual CalculationMethod CalculationMethod { get; set; }
        public virtual decimal TripDistance { get; set; }
        public virtual DateTime LastReceived { get; set; }
    }

    public class CalculatedTripDistanceTimeout { }
}
-- Create table
create table TRIPDISTANCEDATA
(
  id                      RAW(16) not null,
  calculationmethod       NUMBER(10),
  tripdistance            NUMBER(19,5),
  lastreceived            TIMESTAMP(4),
  tripdistancesagadata_id RAW(16)
)
tablespace DM_RW2_TS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table TRIPDISTANCEDATA
  add primary key (ID)
  using index 
  tablespace DM_RW2_TS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table TRIPDISTANCEDATA
  add constraint FK6A3B40123B977EFE foreign key (TRIPDISTANCESAGADATA_ID)
  references TRIPDISTANCESAGADATA (ID);

-- Create table
create table TRIPDISTANCESAGADATA
(
  id                RAW(16) not null,
  myversion         NUMBER(10) not null,
  originalmessageid NVARCHAR2(255),
  originator        NVARCHAR2(255),
  tripkey           NUMBER(20),
  sourcekey         NUMBER(19,5),
  invaliddistance   NUMBER(1),
  startlatitude     NUMBER(19,5),
  startlongitude    NUMBER(19,5),
  endlatitude       NUMBER(19,5),
  endlongitude      NUMBER(19,5),
  iscreated         NUMBER(1)
)
tablespace DM_RW2_TS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table TRIPDISTANCESAGADATA
  add primary key (ID)
  using index 
  tablespace DM_RW2_TS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table TRIPDISTANCESAGADATA
  add unique (TRIPKEY)
  using index 
  tablespace DM_RW2_TS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );

**Comment by ramonsmits** [comment]
Upon inspection the index creation on child collections is happening from v8.0.0+ and only for child collections that have an Id property.

In the future we probably add support for creating index on child collections for items without an Id property as is shown in #350
