### ISSUE TITLE
How to get NH to use an existing IDbTransaction

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus.NHibernate#38]
So the issue is:
- SQLServer transport creates an `IDbConnection` and also an `IDbTransaction` 
- Those instances remain open for the duration of the request
- NHibernate can easily use the `IDbConnection` but it doesn't look like it can use the existing `IDbTransaction`, see https://nhibernate.jira.com/browse/NH-1855

I actually don't know for sure if we even need to share the same transaction as the SQLServer transport or not?

@andreasohlund @johannesg thoughts?

**Comment by johnsimons** [comment]
We have decided to throw a better exception

**Comment by SzymonPobiega** [comment]
There is one big advantage actually. One cannot use Outbox when using ambient transactions. This means one cannot use SQLTransport multi-db feature without DTC. I'll take a look at `ITransactionFactory` again.

**Comment by SzymonPobiega** [comment]
I did a small spike in order to be absolutely sure we can/cannot do this and it seems like it is very unlikely that without resorting to High Magic (passing arguments to a method via thread-static objects) we can do this.

I did implement an `ITransactionFactory` that uses an existing `IDbTransaction` and I would be able to expose session with such a transaction factory to the user but because of the fact that this session has been constructed using an existing connection, it would (silently) not support _2nd level cache_ despite all the correct config etc. The bloker is (this line](https://github.com/nhibernate/nhibernate-core/blob/master/src/NHibernate/Impl/SessionFactoryImpl.cs#L477)

I proved that Outbox can be enabled without the need to suppress ambient transactions so closing this.
