### ISSUE TITLE
When using Outbox user data access transaction completes even though there was an exception in the handler

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.NHibernate#86]
### Symptoms

User data updates are executed multiple times in case an exception happens in the handler.

### Who's affected

All users who enable Outbox except those who run latest SQL Server transport (2.1) with NHibernate 6.1

### Root cause

This is because `TryGet` from outbox store in the `OutboxDeduplicationBehavior` is accessing `LazySqlConnection` causing a new connection to be created before the `TransactionScope` is started and that connection is reused for user data (and saga data).

### Proposed solution

Disable connection sharing in the `TryGet` method.

**Comment by johnsimons** [comment]
Doesn't the `TransactionScope` gets created and wraps `OutboxDeduplicationBehavior` ?

**Comment by mariusin79** [comment]
Exactly how broad should this disable be? If I remember it correctly, the initiation of DbConnections from NServiceBus was introducted due to the faulted connection pool bug in Nhibernate (https://nhibernate.jira.com/browse/NH-3023). If you mean that the Outbox.TryGet operation should initiate its own connection that might work, but if you are suggesting a broader disabling I am concerned with potential side-effects.

@johnsimons: No, a transaction scope is supressed before pipeline-execution because Outbox sets the flag "DoNotWrapHandlersExecutionInATransactionScope"

Regards

Marius Ingjer

**Comment by SzymonPobiega** [comment]
@mariusin79 NHibernate 6.1 actually fixes that and the outbox works fine (confirmed it with Rabbit for now). The caveat is, with 6.1 and outbox `NHibernateStorageContext` is no longer available so you need to create your own `ISession` and `ITransaction` when doing each data access. I will update the sample soon.

I am opening another issue since `NHibernateStorageContext` should not disappear in the minor release.

**Comment by SzymonPobiega** [comment]
@mariusin79 how does manually creating connections relate to NH-3023? I read the bug description but I understood that the actual bug is in ADO and the fact that we create the connection won't affect the race condition between deadlock and releasing connection

**Comment by mariusin79** [comment]
@SzymonPobiega ADO.Net requires a database connection to be opened and closed on the same thread, this is by design so whether this is a nhibernate or ado bug is a matter of definition. You fixed this previously by manually creating connections: https://github.com/Particular/NServiceBus.NHibernate/issues/1

**Comment by SzymonPobiega** [comment]
Fixed via #89 . The NH's connection management is used only when using outbox *and* SQL Server transport. In such case:
 * when using NH's native transactions (inside outbox `TransactionScope`) the behavior is correct (only one BEGIN TRAN is issued against the database)
 * when not using NH's native transactions and relying on `AdoNetWithDistributedTransactionFactory` to call `Flush()` the behavior is correct since single-phase enlistment calls `TransactionScope` events on same thread that opens/closes the scope (avoids #1 )
