### ISSUE TITLE
NHibernatePersistence: if a field is too long the saga data table is not created and there is no error message

### ISSUE THREAD

**Issue by pablocastilla** [Particular/NServiceBus.NHibernate#93]
Today we have had a strange problem, we changed something in the SagaData and its table stopped of being created. The main problem is that it didn't show any error or warning in the console when debugging or when installing the service.

Here you can find a code to reproduce the problem. If you shorten the field in the saga data the table is created.

https://github.com/pablocastilla/SagaDataLongFieldIssue

**Comment by johnsimons** [comment]
It seems column names in oracle can only be a max of 30 characters

**Comment by johnsimons** [comment]
@pablocastilla I've attached the debugger and set "Break on all exceptions" to ON.
Unfortunately nothing blows up :disappointed: 

I'm struggling to figure out how to address this issue, the reason is because when I test this against MS SqlServer it works fine, it seems the restriction on max column length is vendor specific and because we are a framework I want to avoid having vendor specific code.

This also seems to be a well documented restriction in Oracle, see http://stackoverflow.com/questions/756558/what-is-the-maximum-length-of-a-table-name-in-oracle

I know this is not what you want to hear but the only recommendation I have is for you to write a unit test that validates that class names and prop names are <= then 30 characters.
I know it sucks and if you can think of a better way for us to address this issue please let us know.

Thoughts ?

**Comment by pablocastilla** [comment]
ummmmmmmmmm, maybe this helps, I see an exception but I don't know if it is catched in NH or NSB. 

![image](https://cloud.githubusercontent.com/assets/8155105/7313847/4354c55a-ea5e-11e4-87f1-e61e3eec7a43.png)

**Comment by johnsimons** [comment]
Got it @pablocastilla  :smile:

**Comment by johnsimons** [comment]
So I have modified the schema updater to throw an exception if it fails.
Here is an example of the exception:
```c#
System.Exception: Schema update failed.
The following exception(s) were thrown:
System.AggregateException: One or more errors occurred. ---> Oracle.DataAccess.Client.OracleException: ORA-00972: identifier is too long
   at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Oracle.DataAccess.Client.OracleException ORA-00972: identifier is too long    at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, String procedure, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, Boolean bCheck)
   at Oracle.DataAccess.Client.OracleCommand.ExecuteNonQuery()
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)<---


TSql Script:

    create table TestSaga (
        Id RAW(16) not null,
       Originator NVARCHAR2(255),
       OriginalMessageId NVARCHAR2(255),
       SomeId NVARCHAR2(255),
       fddhsfkjdhsgfjkdshkjashdkjdjlasdasldjkldhaskdljahsdkags NVARCHAR2(255),
       primary key (Id)
    )
```
